services:

  bot-app:
      build: .
      image: bot-app-image
      container_name: bot-app-container
      ports:
        - "8081:8081"
      depends_on:
        bot-db:
          condition: service_started
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://bot-db:5432/bot_db
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: pass

  bot-db:
    image: postgres:14.4-alpine
    container_name: bot-db-container
    restart: always
    volumes:
      - bot-db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  bot-db: