spring:
  application:
    name: bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/bot_db}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:pass}
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        show_sql: false
        ddl-auto: none
weather-bot:
  name: ${BOT_NAME:kormilcev_weather_bot}
  token: ${BOT_TOKEN:7864182374:AAF9cXmYfY2pr4KUmQxQoYGMVJqMt1_VlSI}
  key: ${API_KEY:d7f5f33c78d9c01c836e409dae8e4d09}
logging:
  level:
    ru.kormilcev.bot.util.LoggingAspect: info