spring:
  application:
    name: bot
  config:
    import: file:src/main/resources/env.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/bot_db}
    username: ${POSTGRES_USERNAME:user}
    password: ${POSTGRES_PASSWORD:pass}
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        show_sql: false
        ddl-auto: none
weather-bot:
  name: ${bot.name}
  token: ${bot.token}
  key: ${key}
logging:
  level:
    ru.kormilcev.bot.util.LoggingAspect: info